const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),{webcrypto}=require('node:crypto');
// Asynchronous IndexedDB contract double: commits atomically and shares state across page instances.
function database(){
 const stores=new Map();let fail=false;
 const indexedDB={open(){const request={};setImmediate(()=>{request.result={createObjectStore(name){stores.set(name,new Map());},close(){},transaction(names,mode){const tx={},draft=new Map(names.map(n=>[n,new Map(stores.get(n))])),operations=[];tx.objectStore=name=>({put(value){operations.push(()=>draft.get(name).set(value.id,value));},delete(id){operations.push(()=>draft.get(name).delete(id));},get(id){const r={};operations.push(()=>{r.result=draft.get(name).get(id);r.onsuccess?.();});return r;},getAll(){const r={};operations.push(()=>{r.result=[...draft.get(name).values()];r.onsuccess?.();});return r;}});setImmediate(()=>{if(fail&&mode==='readwrite'){tx.error=Error('Quota exceeded');tx.onabort();return;}for(const operation of operations)operation();if(mode==='readwrite')for(const [name,values]of draft)stores.set(name,values);tx.oncomplete();});return tx;}};if(!stores.size)request.onupgradeneeded();request.onsuccess();});return request;}};
 return {indexedDB,set fail(value){fail=value;}};
}
function load(db){const context={indexedDB:db.indexedDB,crypto:webcrypto,TextEncoder};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../piano/library.js'),'utf8'),context);return context.PianoLibrary;}
test('saved XML survives a new page instance, deduplicates content, and supports removal',async()=>{const db=database(),a=load(db);const item=await a.save({xml:'<score/>',title:'Piano',name:'piano.mxl'});const b=load(db);assert.equal((await b.list()).length,1);assert.equal((await b.get(item.id)).xml,'<score/>');await b.save({xml:'<score/>',title:'Piano',name:'piano.xml'});assert.equal((await b.list()).length,1);await b.remove(item.id);assert.equal((await a.list()).length,0);assert.equal(await a.get(item.id),null);});
test('failed write rejects and leaves previous scores intact',async()=>{const db=database(),library=load(db);await library.save({xml:'old',title:'Old',name:'old.xml'});db.fail=true;await assert.rejects(library.save({xml:'new',title:'New',name:'new.xml'}),/Quota/);assert.equal((await library.list()).length,1);assert.equal((await library.list())[0].title,'Old');});
